### ISSUE TITLE
Error with m4pie.py - AttributeError: 'NoneType' object has no attribute 'groupdict'

### ISSUE THREAD

**Issue by pdemaayer** [esrice/PBJelly#1]
Greetings, 

I am running PBJelly to fill gaps in a Canu assembled bird genome with raw PacBio CCS reads. Setup works fine and blasr part of mapping works fine but I get the following error during the m4pie.py step. I've tried running them independently but end up with the same issues. I tried with a small subset of reads and the output is below.

Any help with this would be greatly appreciated!
Pieter

Mapping.chunk0.err looks as follows:

[INFO] 2022-09-22T09:02:41 [blasr] started.
[INFO] 2022-09-22T09:26:33 [blasr] ended.
2022-09-22 09:26:34,232 [INFO] Running /home/pieter/anaconda3/bin/m4pie.py /media/pieter/TOSHIBA1/YBD-Genome/081021PDgenome_Assembly_CCS-HiFi_Reads/All_CCS_Reads/YBDCAN/YBHifi/PDBJ3/mapping/YBDcancorrtest.fasta.m4 /media/pieter/TOSHIBA1/YBD-Genome/081021PDgenome_Assembly_CCS-HiFi_Reads/All_CCS_Reads/YBDCAN/YBHifi/Raw/YBDcancorrtest.fasta /media/pieter/TOSHIBA1/YBD-Genome/081021PDgenome_Assembly_CCS-HiFi_Reads/All_CCS_Reads/YBDCAN/YBHifi/YBDhif.contigs.fasta --nproc 100 -i
2022-09-22 09:26:34,548 [INFO] Extracting tails
2022-09-22 09:26:34,629 [INFO] Parsed 16670 reads
2022-09-22 09:26:34,630 [INFO] Found 9608 tails
2022-09-22 09:26:34,630 [INFO] 1988 reads had double tails
2022-09-22 09:26:34,630 [INFO] Mapping Tails
2022-09-22 10:12:33,467 [INFO] [0, '[INFO] 2022-09-22T09:26:34 [blasr] started.\n[INFO] 2022-09-22T10:12:33 [blasr] ended.\n', None]
2022-09-22 10:12:33,468 [INFO] Consolidating alignments
Traceback (most recent call last):
  File "/home/pieter/anaconda3/bin/m4pie.py", line 4, in <module>
    __import__('pkg_resources').run_script('pbjelly==16.0b1', 'm4pie.py')
  File "/home/pieter/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/pieter/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/home/pieter/anaconda3/lib/python3.8/site-packages/pbjelly-16.0b1-py3.8.egg/EGG-INFO/scripts/m4pie.py", line 212, in <module>
    run(sys.argv[1:])
  File "/home/pieter/anaconda3/lib/python3.8/site-packages/pbjelly-16.0b1-py3.8.egg/EGG-INFO/scripts/m4pie.py", line 208, in run
    n = uniteTails(aligns, tailmap, args.output, args.inplace)
  File "/home/pieter/anaconda3/lib/python3.8/site-packages/pbjelly-16.0b1-py3.8.egg/EGG-INFO/scripts/m4pie.py", line 120, in uniteTails
    data = datGrab.search(read.qname).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'

Protocol.xml looks as follows:
<jellyProtocol>
    <reference>/media/pieter/TOSHIBA1/YBD-Genome/081021PDgenome_Assembly_CCS-HiFi_Reads/All_CCS_Reads/YBDCAN/YBHifi/YBDhif.contigs.fasta</reference>  
    <outputDir>/media/pieter/TOSHIBA1/YBD-Genome/081021PDgenome_Assembly_CCS-HiFi_Reads/All_CCS_Reads/YBDCAN/YBHifi/PDBJ3/</outputDir>
    <cluster>
        <command notes="For single node, multi-core machines" >${CMD} ${JOBNAME} 2> ${STDERR} 1> ${STDOUT} &amp;</command>
        <nJobs>1</nJobs>
    </cluster>
    <blasr>--minMatch 8 --sdpTupleSize 8 --minPctIdentity 75 --bestn 1 --nCandidates 10 --maxScore -500 --nproc 100 --noSplitSubreads</blasr>
    <input baseDir="/media/pieter/TOSHIBA1/YBD-Genome/081021PDgenome_Assembly_CCS-HiFi_Reads/All_CCS_Reads/YBDCAN/YBHifi/Raw">
        <job>YBDcancorrtest.fasta</job>
    </input>
</jellyProtocol>
[Protocoltextversion.txt](https://github.com/esrice/PBJelly/files/9626806/Protocoltextversion.txt)

**Comment by pdemaayer** [comment]
Sorry, it somehow stripped the Protocol.xml, it is as follows:

<jellyProtocol>
    <reference>/media/pieter/TOSHIBA1/YBD-Genome/081021PDgenome_Assembly_CCS-HiFi_Reads/All_CCS_Reads/YBDCAN/YBHifi/YBDhif.contigs.fasta</reference>  
    <outputDir>/media/pieter/TOSHIBA1/YBD-Genome/081021PDgenome_Assembly_CCS-HiFi_Reads/All_CCS_Reads/YBDCAN/YBHifi/PDBJ3/</outputDir>
    <cluster>
        <command notes="For single node, multi-core machines" >${CMD} ${JOBNAME} 2> ${STDERR} 1> ${STDOUT} &amp;</command>
        <nJobs>1</nJobs>
    </cluster>
    <blasr>--minMatch 8 --sdpTupleSize 8 --minPctIdentity 75 --bestn 1 --nCandidates 10 --maxScore -500 --nproc 100 --noSplitSubreads</blasr>
    <input baseDir="/media/pieter/TOSHIBA1/YBD-Genome/081021PDgenome_Assembly_CCS-HiFi_Reads/All_CCS_Reads/YBDCAN/YBHifi/Raw">
        <job>YBDcancorrtest.fasta</job>
    </input>
</jellyProtocol>

**Comment by esrice** [comment]
Sorry it took me a while to respond — I was on vacation.

This repository was something I hacked together in 2018 to try to get PBJelly, which had already by then been unsupported for three years, to work with the most recent versions of the software it depended on. Now PBJelly has been unsupported for seven years, and there are better gap closers out there that are still supported, e.g.,

Dentist: https://pubmed.ncbi.nlm.nih.gov/35077539/
TGS-Gapcloser https://academic.oup.com/gigascience/article/9/9/giaa094/5902284

Sorry that I can't help fix this bug in the software, but I don't use this gap closer anymore myself. I hope these suggestions of alternate software are helpful, though!

**Comment by pdemaayer** [comment]
Greetings Edward,

No worries at all. Thanks for letting me know 😊, will give those tools a whirl.

Thanks and regards
Pieter

***@***.***
Prof Pieter De Maayer
Associate Professor
School of Molecular & Cell Biology
Biological Sciences Chair
University of the Witwatersrand

Phone +27 (0)11 717 6322  Mobile +27 (0)72 792 4826
Email ***@***.******@***.***>
Web   ***@***.*** <https://scholar.google.com/citations?user=G0Lo1DgAAAAJ&hl=en>      ***@***.*** <https://www.researchgate.net/profile/Pieter_De_Maayer>
Private Bag 3, WITS, 2050, Johannesburg
